version: "3.9"

services:
  nonogram-socket-backend:
    build: .
    image: nonogram-backend
    container_name: "nonogram-backend"
    restart: always
    environment:
      BEREND: yep
      DATABASE_URL: file:./test.db
    ports:
      - "7100:7100"
      - "7200:7200"
    command: >
      bash -c "npm run serve"
    networks:
      - 'caddy'
    volumes:
      - ./db:/usr/src/app/db

networks:
  caddy:
    name: 'caddy'
